import os 
import hashlib
import json
import time
import sys

hash_file = "hashfile.json"

def calchash(fp): #fp stand for file path
    hash = hashlib.sha256()  #creates empty hash object
    try:
        with open(fp,"rb") as f: # because hashlib works on binary
            hash.update(f.read()) # giving the binary content of file to sha256 engine
            return hash.hexdigest() #convert binary hash to 64 characters human readable form
    except(PermissionError,FileNotFoundError):
        None
   
# test_filename = "demo_target.txt"
# with open(test_filename,"w") as f: # this will create a new file because in write mode
#     f.write("test file")    #insert "test file" in the file
# resulthash  = calchash(test_filename) 
# print(resulthash)
# absolute_path = os.path.abspath(test_filename) #store path of file in variable
# print(absolute_path)
d = {}
for root,dirs,files in os.walk("/home/kali/Documents"): # os.walk creates a generator which is capable of generating file paths
    # print(root)                                        # when python prints a list 
    # print(dirs)                                        # so python loads data into ram and computer contains many files can outrun of ram and freeze the os
    # print(files)                                        # that's why os.walk returns generator not a complete list
    # print("-"*40)                                      # threee variables are required to print the data generated by generator
                                                       # root is a string of parent directory
                                                       # dirs is a list of all directories inside parent directory
                                                       # file is a list of all files inside parent directory
    for file in files:
        #file_hash = calchash(root+"/"+file) not a good practice
        full_path = os.path.join(root,file) # this  is good practice
        file_hash = calchash(full_path) 
        # print(file_hash)
        d[full_path] = file_hash
with open(hash_file,"w") as hf:
        json.dump(d,hf,indent=4)

while(True):
     live = {}
     for root,dirs,files in os.walk("/home/kali/Documents"):
          for file in files:
                full_path = os.path.join(root,file) 
                file_hash = calchash(full_path) 
                live[full_path] = file_hash
     with open(hash_file, "r") as f:
          a = f.read()
          a = json.loads(a)             # converts json string into python object
          for k in a:
               if k not in live:
                    print("file deleted : ",k)
               elif k in live:
                    if a[k] != live[k]:
                        print("file modified : ",k)
                    else:
                         continue
                
          for k in live:
               if k not in a:
                    print("new file created : ",k)
                             
     time.sleep(5)


    
          
          
     